name: black_attack
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.31.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==23.2.0
    - certifi==2024.6.2
    - charset-normalizer==3.4.3
    - click==8.2.1
    - comm==0.2.2
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==2.19.2
    - decorator==5.2.1
    - diffusers==0.20.2
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.1
    - executing==2.2.1
    - filelock==3.14.0
    - fonttools==4.60.1
    - frozenlist==1.7.0
    - fsspec==2024.3.1
    - gitdb==4.0.12
    - gitpython==3.1.45
    - huggingface-hub==0.23.3
    - idna==3.7
    - importlib-metadata==8.4.0
    - ipython==8.25.0
    - ipywidgets==8.1.3
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - jupyterlab-widgets==3.0.11
    - kiwisolver==1.4.9
    - markupsafe==2.1.5
    - matplotlib==3.10.6
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - multidict==6.6.4
    - multiprocess==0.70.16
    - networkx==3.3
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - opacus==1.4.1
    - opt-einsum==3.3.0
    - packaging==25.0
    - pandas==2.2.2
    - parso==0.8.5
    - peft==0.11.1
    - pexpect==4.9.0
    - pillow==11.3.0
    - pip==24.0
    - platformdirs==4.2.2
    - prompt-toolkit==3.0.47
    - propcache==0.3.2
    - protobuf==5.29.5
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.7
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pygments==2.18.0
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytorch-fid==0.3.0
    - pytz==2024.1
    - pyyaml==6.0.2
    - regex==2024.5.15
    - requests==2.32.3
    - safetensors==0.4.3
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - sentry-sdk==2.5.1
    - setproctitle==1.3.6
    - setuptools==69.5.1
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - sympy==1.12.1
    - threadpoolctl==3.5.0
    - tokenizers==0.19.1
    - torch==2.1.0+cu121
    - torchaudio==2.1.0+cu121
    - torchdata==0.7.0
    - torchtext==0.16.0+cpu
    - torchvision==0.16.0+cu121
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transformers==4.41.2
    - triton==2.1.0
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - urllib3==2.2.1
    - wandb==0.17.1
    - wcwidth==0.2.13
    - wheel==0.43.0
    - widgetsnbextension==4.0.11
    - xxhash==3.5.0
    - yarl==1.20.1
    - zipp==3.19.2
prefix: /root/miniconda3/envs/black_attack
